// <auto-generated />
namespace AngularChatApp20SepNight.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mi20sepnight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mi20sepnight));
        
        string IMigrationMetadata.Id
        {
            get { return "202009201541106_mi20sepnight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
